/**
 * Turn a workflow's JSON result into the typed content modules under
 * `src/content/nanyang-r1/`.
 *
 *   node scripts/gen-content.mjs <path-to-workflow-task.output>
 *
 * The workflows return validated JSON, so the only job here is emitting it as
 * TypeScript that matches `src/content/types.ts`. It is a generator and not a
 * hand-write because there are ~111 concepts with embedded code blocks, and
 * hand-transcribing those is exactly how a stray backtick or a dropped escape
 * gets into revision material the day before an interview.
 *
 * Multi-line strings become template literals (so code blocks stay readable in
 * the editor); anything containing a backtick, a `${`, or a backslash falls back
 * to JSON.stringify, which is always safe.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = resolve(here, '../src/content/nanyang-r1');

const src = process.argv[2];
if (!src) {
  console.error('usage: node scripts/gen-content.mjs <workflow-task.output>');
  process.exit(1);
}

const payload = JSON.parse(readFileSync(src, 'utf8'));
const raw = payload.result ?? payload;

/* The two content workflows named the same things differently — the behavioral
   one returns `questions` and `claims` where the technical one returns `bank`
   and `consistency`. Normalize here rather than at 40 call sites below. */
const result = {
  ...raw,
  bank: raw.bank ?? raw.questions,
  consistency: raw.consistency ?? raw.claims,
};

/* ------------------------------------------------------------------ litter */

function lit(v) {
  if (typeof v === 'number' || typeof v === 'boolean' || v === null) return String(v);
  if (typeof v !== 'string') return JSON.stringify(v);
  if (!v.includes('\n')) return JSON.stringify(v);
  if (v.includes('`') || v.includes('${') || v.includes('\\')) return JSON.stringify(v);
  return '`' + v + '`';
}

const KEY_OK = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

/** Emit an object literal, one field per line, fields in the given order. */
function obj(o, fields, indent) {
  const pad = ' '.repeat(indent);
  const inner = ' '.repeat(indent + 2);
  const lines = [];
  for (const f of fields) {
    if (!(f in o) || o[f] === undefined) continue;
    const key = KEY_OK.test(f) ? f : JSON.stringify(f);
    const v = o[f];
    if (Array.isArray(v)) {
      if (v.length === 0) {
        lines.push(`${inner}${key}: [],`);
      } else if (v.every((x) => typeof x === 'string')) {
        lines.push(`${inner}${key}: [`);
        for (const x of v) lines.push(`${inner}  ${lit(x)},`);
        lines.push(`${inner}],`);
      } else {
        lines.push(`${inner}${key}: [`);
        for (const x of v) lines.push(obj(x, Object.keys(x), indent + 4) + ',');
        lines.push(`${inner}],`);
      }
    } else if (v && typeof v === 'object') {
      lines.push(`${inner}${key}: ${obj(v, Object.keys(v), indent + 2).trimStart()},`);
    } else {
      lines.push(`${inner}${key}: ${lit(v)},`);
    }
  }
  return `${pad}{\n${lines.join('\n')}\n${pad}}`;
}

function emit({ file, header, name, type, items, fields }) {
  const body = items.map((it) => obj(it, fields, 2)).join(',\n');
  const text = `${header}\nexport const ${name}: ${type} = [\n${body},\n];\n`;
  writeFileSync(resolve(OUT_DIR, file), text, 'utf8');
  console.log(`wrote ${file} — ${items.length} entries, ${text.length} chars`);
}

/* ------------------------------------------------------------------ topics */

if (Array.isArray(result.topics) && result.topics.length) {
  emit({
    file: 'topics.ts',
    name: 'topics',
    type: 'Topic[]',
    items: result.topics,
    fields: [
      'id',
      'title',
      'tagline',
      'jdHook',
      'priority',
      'stance',
      'stanceNote',
      'estMinutes',
      'bridgeIfUnknown',
      'concepts',
      'questions',
      'flashcards',
      'traps',
    ],
    header: `import type { Topic } from '../types';

/**
 * Technical revision material, one entry per thing the JD asks for.
 *
 * GENERATED by \`scripts/gen-content.mjs\` from the technical-content workflow
 * (11 topics, each authored then adversarially checked by two independent
 * lenses and revised). Hand edits are fine; they are lost on regeneration.
 *
 * \`stance\` is his ACTUAL position, not aspiration:
 *   strong  — he has shipped this, can be questioned deeply
 *   partial — adjacent experience, can reason about it, has not owned it
 *   gap     — has not done it; \`bridgeIfUnknown\` is the honest sentence
 *
 * Nothing here may invent experience. A \`gap\` topic still gets full concepts and
 * questions — knowing the material is not the same as claiming the résumé line,
 * and the interview reward is understanding the vocabulary well enough to hold a
 * conversation while being straight about never having shipped it.
 */`,
  });
}

/* ------------------------------------------------------------------- stars */

if (Array.isArray(result.stars) && result.stars.length) {
  emit({
    file: 'stars.ts',
    name: 'stars',
    type: 'Star[]',
    items: result.stars,
    fields: [
      'id',
      'title',
      'company',
      'period',
      'priority',
      'status',
      'oneLiner',
      'useFor',
      'openWith',
      'situation',
      'task',
      'action',
      'result',
      'landingLine',
      'boundaries',
      'scopeGuard',
      'followUps',
    ],
    header: `import type { Star } from '../types';

/**
 * The stories, in STAR shape.
 *
 * GENERATED by \`scripts/gen-content.mjs\`. \`scopeGuard\` is not decoration: he
 * proposed and owned modules, he did not architect platforms, and every story
 * here carries the sentence that keeps the claim inside what he actually did.
 */`,
  });
}

/* -------------------------------------------------------------------- bank */

if (Array.isArray(result.bank) && result.bank.length) {
  emit({
    file: 'bank.ts',
    name: 'bank',
    type: 'BankQuestion[]',
    items: result.bank,
    fields: ['id', 'category', 'likelihood', 'q', 'a', 'why', 'trap', 'relatedStar'],
    header: `import type { BankQuestion } from '../types';

/**
 * Every question he is likely to be asked, with an answer he can actually say.
 *
 * GENERATED by \`scripts/gen-content.mjs\`. Model answers never contain his hedge
 * tics — "cũng", "chỉ là", "chưa hẳn", "em nghĩ chắc" — except inside a \`trap\`
 * that names them as the thing to avoid.
 */`,
  });
}

/* ------------------------------------------------------------- consistency */

if (Array.isArray(result.consistency) && result.consistency.length) {
  emit({
    file: 'consistency.ts',
    name: 'consistency',
    type: 'ConsistencyClaim[]',
    items: result.consistency,
    fields: ['id', 'claim', 'where', 'mustDefend', 'risk', 'drillQ', 'drillA'],
    header: `import type { ConsistencyClaim } from '../types';

/**
 * Everything on paper that an interviewer can point at and ask "show me".
 *
 * GENERATED by \`scripts/gen-content.mjs\`. A claim he cannot defend out loud is
 * worse than one he never made, so each row carries the drill that proves it.
 */`,
  });
}

/* ----------------------------------------------------------------- company */

if (result.company) {
  const c = result.company;
  const facts = c.facts.map((f) => obj(f, ['id', 'title', 'body', 'sayThis', 'neverSay', 'confidence', 'source'], 4)).join(',\n');
  const asks = c.questionsToAsk.map((q) => obj(q, ['id', 'q', 'why', 'priority', 'keepIfOnlyFour'], 4)).join(',\n');
  const unknowns = c.unknowns.map((u) => `    ${lit(u)},`).join('\n');
  const text = `import type { CompanyBrief } from '../types';

/**
 * What is actually known about Nanyang Biologics, and what to ask them.
 *
 * GENERATED by \`scripts/gen-content.mjs\`. \`confidence\` is load-bearing: a
 * 'reported' fact is one source's word and must be spoken as such, and
 * 'unknown' items belong in the questions he asks, never in a claim he makes.
 */
export const company: CompanyBrief = {
  facts: [
${facts},
  ],
  questionsToAsk: [
${asks},
  ],
  unknowns: [
${unknowns}
  ],
};
`;
  writeFileSync(resolve(OUT_DIR, 'company.ts'), text, 'utf8');
  console.log(`wrote company.ts — ${c.facts.length} facts, ${c.questionsToAsk.length} questions, ${c.unknowns.length} unknowns`);
}
